import { describe, expect, it } from 'vitest';
import { SCENARIO } from '../src/game/scenario'; import { applyTurn, derivePortraitState } from '../src/game/state'; import { classifyAlignment, evaluateOutcome } from '../src/game/outcome'; import { ModelOutputSchema, PlayerIntentSchema, PerceivedImpactSchema } from '../server/turn/schema'; import { TurnRequestSchema } from '../server/turn/validation'; import { processTurn } from '../server/turn/service'; import { MockModelAdapter } from '../server/adapters/MockModelAdapter';

const request=(turnIndex=0)=>({scenarioId:SCENARIO.id,turnIndex,playerText:'I am sorry I hurt you.',selectedIntention:'acknowledge' as const,state:{engagement:-3,tension:1},recentTranscript:[]});
const assessment=(impact:any,alignment:any='aligned')=>({selectedIntent:'acknowledge' as const,perceivedImpact:impact,impactReason:'It landed clearly.',alignment,engagementDelta:0,tensionDelta:0});
describe('dynamic conversation core',()=>{
 it('defines a 15-turn scenario with scenario-owned prologue and no turn script',()=>{expect(SCENARIO.totalTurns).toBe(15);expect(SCENARIO.prologue.join(' ')).toContain('nine years');expect((SCENARIO as any).beats).toBeUndefined();});
 it('validates all four intentions and rejects a missing intention',()=>{for(const i of ['understand','acknowledge','explain','repair'])expect(PlayerIntentSchema.safeParse(i).success).toBe(true);expect(TurnRequestSchema.safeParse({...request(),selectedIntention:undefined}).success).toBe(false);});
 it('validates the complete impact vocabulary and bounded plain reasons',()=>{for(const i of ['understanding','acknowledgment','explanation','repair','defense','minimization','pressure','avoidance','unclear'])expect(PerceivedImpactSchema.safeParse(i).success).toBe(true);expect(ModelOutputSchema.safeParse({characterText:'x',perceivedImpact:'repair',impactReason:'<b>bad</b>',engagementDelta:0,tensionDelta:0}).success).toBe(false);});
 it('blocks a sixteenth request at validation',()=>expect(TurnRequestSchema.safeParse(request(15)).success).toBe(false));
 it('keeps state clamped and has a guarded opening portrait',()=>{expect(derivePortraitState(-3,1)).toBe('distant');const next=applyTurn({engagement:10,tension:-10,portraitState:'connected'},99,-99);expect(next.engagement).toBe(10);expect(next.tension).toBe(-10);});
 it('can reach every portrait deterministically',()=>{expect(new Set([derivePortraitState(-3,1),derivePortraitState(-3,5),derivePortraitState(1,3),derivePortraitState(5,0)])).toEqual(new Set(['distant','defensive','hurt_exposed','connected']));});
 it('computes intent alignment in code',()=>{expect(classifyAlignment('acknowledge','acknowledgment')).toBe('aligned');expect(classifyAlignment('repair','understanding')).toBe('constructive_divergence');expect(classifyAlignment('understand','pressure')).toBe('harmful_divergence');});
 it('keeps all outcomes reachable through accumulated patterns',()=>{const good=Array.from({length:15},()=>assessment('repair'));const bad=Array.from({length:15},()=>assessment('pressure','harmful_divergence'));const middle=Array.from({length:15},()=>assessment('unclear','constructive_divergence'));expect(evaluateOutcome({assessments:good,finalEngagement:5,finalTension:0})).toBe('even');expect(evaluateOutcome({assessments:bad,finalEngagement:-5,finalTension:8})).toBe('the_speech');expect(evaluateOutcome({assessments:middle,finalEngagement:0,finalTension:0})).toBe('smoothed');});
 it('uses one model result including closings only on turn fifteen',async()=>{const a=new MockModelAdapter();const normal=await processTurn(request(),a);expect(normal.finalClosures).toBeUndefined();const final=await processTurn(request(14),a);expect(final.finalClosures?.even).toBeTruthy();});
 it('keeps malformed output playable with deterministic closing fallback',async()=>{const result=await processTurn(request(14),new MockModelAdapter('malformed'));expect(result.assessment.perceivedImpact).toBe('unclear');expect(result.finalClosures).toEqual(SCENARIO.fallbackClosures);});
});
